[[markets]]
slug = "2024-us-presidential-election"
title = "US presidential election"
description = """
# Resolution criteria

Resolves to the person who wins the majority of votes for US President in the
Electoral College, or selected by Congress following the contingency procedure
in the Twelfth Amendment.

Resolves early if both the Associated Press projects a winner and the losing major party candidate concedes.
"""
created_at = 1697838953000000
expires_at = 1730764800000000
books = ["Donald Trump", "Joe Biden", "Nikki Haley", "Ron DeSantis", "Kamala Harris"]

[[markets]]
slug = "2024-us-republican-nominee"
title = "US Republican nominee"
description = """
# Resolution criteria

Resolve to the person who is nominated by the Republican Party to run for US
President in the 2024 election.
"""
created_at = 1697838953000000
expires_at = 1730764800000000
books = ["Donald Trump", "Nikki Haley", "Ron DeSantis"]