[[markets]]
# https://www.metaculus.com/questions/11245/winner-of-2024-us-presidential-election/
slug = "2024-us-presidential-election"
title = "US Presidential Election"
created_at = 1697838953000000
expires_at = 1730764800000000
tags = ["politics", "election"]
description = """
## Resolution criteria

This question will resolve as Yes for the person who wins the 2024 US presidential election,
and No for all other options. This will be the person who wins the majority of votes in the
Electoral College, or selected by Congress following the contingency procedure in the
Twelfth Amendment.
"""
books = [
    "Donald Trump",
    "Joe Biden",
    "Michelle Obama",
    "Robert F. Kennedy Jr.",
    "Kamala Harris",
]


[[markets]]
slug = "2024-us-republican-nominee"
title = "US Republican Nominee"
created_at = 1697838953000000
expires_at = 1730764800000000
tags = ["politics"]
description = """
## Resolution criteria

Resolve to the person who is nominated by the Republican Party to run for US
President in the 2024 election.
"""
books = ["Donald Trump", "Nikki Haley", "Ron DeSantis"]


[[markets]]
slug = "2024-stanley-cup-playoffs"
title = "Stanley Cup Playoffs"
created_at = 1697838953000000
expires_at = 1730764800000000
tags = ["sports", "hockey"]
description = """
## Resolution criteria

This market will resolve to Yes for the team that wins the 2024 Stanley Cup Champion
and No for all other options.
"""
books = [
    "Florida Panthers",
    "Dallas Stars",
    "New York Rangers",
    "Edmonton Oilers",
    "Colorado Avalanche",
    "Boston Bruins",
]

[[markets]]
slug = "2024-06-fed-interest-rate"
title = "Fed interest rate"
created_at = 1697838953000000
expires_at = 1730764800000000
tags = ["economics"]
description = """
## Resolution criteria

The fed is meeting June 11.
"""
books = [
    "No increase",
    "Between 4.75% and 4.99%",
    "Between 5.00% and 5.24%",
]
